name: iOS CI

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Analize and clean
        run: xcodebuild -project "OpenBankTest.xcodeproj" -scheme "OpenBankTest" -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=15.2" clean analyze
      - name: Build
        run: xcodebuild -scheme "OpenBankTest" -project "OpenBankTest.xcodeproj" -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=15.2" build
      - name: Test 
        run: xcodebuild -scheme "OpenBankTest" -project "OpenBankTest.xcodeproj" -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=15.2" test
